apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uuxcqrswp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uuxcqrswp-go 
  name: uuxcqrswp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uuxcqrswp-go 
